[package]
name = "ACVPeppers"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/manczak-ifx/acvpeppers/"

[[bin]]
name="peppers"
path="src/main.rs"

[dependencies]
curl = "0.4.49"
reqwest = { version = "0.12.23", features = ["blocking", "json","native-tls"] }
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.9"
hex = "0.4"
simplelog = "0.12"
serde_json = "1.0.143"
rayon = "1.11.0"
lazy_static = "1.4"
totp-rs = "5.7.0"
base64 = "0.22.1"
hmac = "0.12"
anyhow = "1.0"
url = "2.5.7"
clap = { version = "4.5", features = ["derive","env"] }
log = "0.4"
flexi_logger = {version ="0.27", features=["specfile_without_notification"]}
toml = "0.8"
owo-colors = "4"
colored = "2.1"
once_cell="1.19"
aes = "0.8"
cipher="0.4.4"
cbc ="0.1.2"
ecb="0.1.2"
